name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Install proxymock
      run: sh -c "$(curl -Lfs https://downloads.speedscale.com/proxymock/install-proxymock)"
    
    - name: Initialize proxymock
      run: ~/.speedscale/proxymock init --api-key ${{ secrets.PROXYMOCK_API_KEY }}

    - name: Import snapshot
      run: |
        ~/.speedscale/proxymock import --file .speedscale/snapshot/5e5ad11f-bda5-40b7-b5df-21e6f8effb87.json
        echo 'Using snapshot: $SNAPSHOT_ID'
    
    - name: Run proxymock
      run: |
        ~/.speedscale/proxymock run --snapshot-id $SNAPSHOT_ID &
        sleep 5

    - name: Run tests
      run: go test -v ./...

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to the Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/kenahrens/outerspace-go:latest
