name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Install proxymock
      run: |
        sh -c "$(curl -Lfs https://downloads.speedscale.com/proxymock/install-proxymock)"
        ~/.speedscale/proxymock init --api-key ${{ secrets.PROXYMOCK_API_KEY }}

    - name: Import and run proxymock
      run: |
        ~/.speedscale/proxymock import --file .speedscale/snapshot/raw.jsonl
        FILENAME=$(ls ~/.speedscale/data/snapshots/*.json)
        echo "Snapshot filename: ${FILENAME}"
        SNAPSHOT_ID=$(basename "$FILENAME" .json)
        echo "Using snapshot: $SNAPSHOT_ID"
        ~/.speedscale/proxymock run --snapshot-id $SNAPSHOT_ID & > proxymock.log
        go mod download
        export http_proxy=socks5h://localhost:4140
        export https_proxy=socks5h://localhost:4140
        export SSL_CERT_FILE=~/.speedscale/certs/tls.crt
        go test -v ./...
        cat proxymock.log

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to the Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/kenahrens/outerspace-go:latest
